apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: kube-prometheus-stack
type: Opaque
stringData:
  # Grafana admin credentials
  # Used for Web Console authentication
  admin-user: "admin"
  admin-password: "Password123"
