repositories:
  - name: minio-operator
    url: https://operator.min.io/

helmDefaults:
  createNamespace: true
  wait: true
  timeout: 600

## Document separator to satisfy Helmfile:
---
namespace: minio-tenant

releases:
  - name: minio-tenant
    chart: minio-operator/tenant
    version: 7.1.1
    values:
      - values/minio-tenant.yaml
