repositories:
  - name: longhorn
    url: https://charts.longhorn.io

helmDefaults:
  createNamespace: true
  wait: false
  timeout: 600

---
releases:
  - name: longhorn
    namespace: longhorn
    chart: longhorn/longhorn
    version: 1.10.1
    values:
      - values/longhorn.yaml
