repositories:
  - name: vector
    url: https://helm.vector.dev

helmDefaults:
  createNamespace: true
  wait: true
  timeout: 600

## Document separator to satisfy Helmfile:
---
namespace: kube-system

releases:
  - name: vector
    chart: vector/vector
    version: 0.48.0
    values:
      - values/vector.yaml
