repositories:
  - name: vector
    url: https://helm.vector.dev

helmDefaults:
  createNamespace: true
  wait: true
  timeout: 600

## Document separator to satisfy Helmfile:
---
releases:
  - name: vector
    namespace: kube-system
    chart: vector/vector
    version: 0.46.0
    values:
      - values/vector.yaml
