repositories:
  - name: cilium
    url: https://helm.cilium.io

helmDefaults:
  createNamespace: true
  wait: true
  timeout: 600

## Document separator to satisfy Helmfile:
---
namespace: kube-system

releases:
  - name: cilium
    chart: cilium/cilium
    version: 1.18.3
    values:
      - values/cilium.yaml
