repositories:
  - name: localpath
    url: https://charts.containeroo.ch
  - name: rustfs
    url: https://charts.rustfs.com

helmDefaults:
  createNamespace: true
  wait: false
  timeout: 600

## Document separator to satisfy Helmfile:
---
releases:
  # - name: local-path-provisioner
  #   namespace: local-path-provisioner
  #   chart: localpath/local-path-provisioner
  #   version: 0.0.33
  #   values:
  #     - values/localpath.yaml

  - name: rustfs
    chart: rustfs/rustfs
    namespace: rustfs
    version: 0.0.73
    values:
      - values/rustfs.yaml
    # needs:
    #   - local-path-provisioner/local-path-provisioner
