apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: etcd-workbench
  annotations:
    external-dns.alpha.kubernetes.io/target: 10.0.0.230
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`etcd.k8s.tier.f5.si`)
      services:
        - name: etcd-workbench
          port: 8002
      middlewares:
        - name: traefik-redirect-https@kubernetescrd
