apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-workbench
  template:
    metadata:
      labels:
        app: etcd-workbench
    spec:
      containers:
        - name: etcd-workbench
          image: docker.io/tzfun/etcd-workbench:latest
          ports:
            - containerPort: 8002
              protocol: TCP
