replicaCount: 3

ingress:
  className: traefik
  traefikAnnotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: rustfs.k8s.tier.f5.si
      paths:
        - path: /
          pathType: ImplementationSpecific

containerSecurityContext:
  readOnlyRootFilesystem: false
