image:
  repository: docker.io/rcourtman/pulse
  tag: 4.36.1

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: pulse.k8s.tier.f5.si
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  storageClass: longhorn-rwx
  accessModes:
    - ReadWriteMany
  size: 5Gi

server:
  env:
    - name: TZ
      value: Asia/Tokyo
