apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filebrowser
  annotations:
    external-dns.alpha.kubernetes.io/target: 10.0.0.230
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`filebrowser.k8s.tier.f5.si`)
      services:
        - name: filebrowser
          port: 80
