repositories:
  - name: traefik
    url: https://traefik.github.io/charts
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns
  - name: minio-operator
    url: https://operator.min.io/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

helmDefaults:
  createNamespace: true
  wait: false
  timeout: 600

## Document separator to satisfy Helmfile:
---
releases:
  - name: traefik-crds
    chart: traefik/traefik-crds
    version: 1.12.0

  - name: prometheus-operator-crds
    namespace: kube-prometheus-stack
    chart: prometheus-community/prometheus-operator-crds
    version: 24.0.2

  - name: metrics-server
    namespace: metrics-server
    chart: metrics-server/metrics-server
    version: 3.13.0
    values:
      - values/metrics-server.yaml

  - name: external-dns
    namespace: external-dns
    chart: external-dns/external-dns
    version: 1.19.0
    values:
      - values/external-dns.yaml

  - name: minio-operator
    namespace: minio-operator
    chart: minio-operator/operator
    version: 7.1.1
    values:
      - values/minio-operator.yaml
