apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  annotations:
    external-dns.alpha.kubernetes.io/target: 10.0.0.230
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`portainer.k8s.tier.f5.si`)
      services:
        - name: portainer
          port: 9443
          serversTransport: portainer-insecure-transport
