---
- name: Setup Proxy VMs
  hosts: proxy
  become: true
  roles:
    - 02-basic-vms/proxy

- name: Setup DNS VMs
  hosts: dns
  become: true
  roles:
    - 02-basic-vms/dns

- name: Setup Keycloak VMs
  hosts: keycloak
  become: true
  roles:
    - 02-basic-vms/keycloak
