---
- name: Package upgrade
  hosts: all
  become: true
  tasks:
    - name: Package upgrade on systems using apt
      apt:
        name: "*"
        state: latest # noqa: package-latest  # noqa: package-latest
      when: ansible_os_family == "Debian"

    - name: Package upgrade on systems using dnf
      dnf:
        name: "*"
        state: latest # noqa: package-latest  # noqa: package-latest
      when: ansible_os_family == "RedHat"
