repositories:
  - name: strrl.dev
    url: https://helm.strrl.dev

helmDefaults:
  createNamespace: true
  wait: true
  timeout: 600

## Document separator to satisfy Helmfile:
---
namespace: cloudflare-tunnel-ingress-controller

releases:
  - name: cloudflare-tunnel-ingress-controller
    chart: strrl.dev/cloudflare-tunnel-ingress-controller
    version: 0.0.21
    values:
      - values/cf-tunnel-ingress-controller.yaml
